# Generated by Django 3.1.4 on 2021-01-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_status',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
